config/routes.rb
# RouteSet
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: "users/sessions"
  }
  root "pages#home"
  get "/check_credential", to: "pages#credential"
  get "/promos", to: "pages#promos"

  get "/about", to: "pages#about_us"
  get "/ready_for_occupancy", to: "pages#ready_for_occupancy"
  get "/pre_selling", to: "pages#pre_selling"
  get "/unit/:id", to: "pages#unit", as: :unit
  get "/sellers", to: "sellers#index"

  resources :contact, only: [:new]
  get "/contact", to: "contact#create"

  mount RailsAdmin::Engine => "/admin", as: "rails_admin"

  # get "*unmatched_route", to: "application#raise_not_found"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_carousel.html.haml
%br/
#carouselExampleFade.carousel.slide.carousel-fade{"data-ride" => "carousel"}
  .carousel-inner
    - @carousels.each do |carousel|
      .carousel-item{ class: "#{carousel.id}" }
        %img.d-block.w-100{alt: "First slide", src: "#{carousel.try(:image).to_s}", class: "#{carousel.try(:id)}", style: "height:500px"}/
  %a.carousel-control-prev{"data-slide" => "prev", href: "#carouselExampleFade", role: "button"}
    %span.carousel-control-prev-icon{"aria-hidden" => "true"}
    %span.sr-only Previous
  %a.carousel-control-next{"data-slide" => "next", href: "#carouselExampleFade", :role => "button"}
    %span.carousel-control-next-icon{"aria-hidden" => "true"}
    %span.sr-only Next
  :javascript
      $('.1').addClass('active')

app/views/shared/_footer.html.haml
%br/
/ Footer
%footer.page-footer.font-small.darken-3{ :style => "background-color:#449c3c" }
  / Footer Elements
  .container
    / Grid row
    .row
      / Grid column
      .col-md-12.py-5
        .mb-5.flex-center
          / Facebook
          %a.fb-ic{:href => "https://web.facebook.com/AyalaLandPropertiesBestDeals?_rdc=1&_rdr"}
            %i.fab.fa-facebook-f.fa-lg.white-text.mr-md-5.mr-3.fa-2x
          / Twitter
          -# %a.tw-ic
          -#   %i.fab.fa-twitter.fa-lg.white-text.mr-md-5.mr-3.fa-2x
          -# / Google +
          -# %a.gplus-ic
          -#   %i.fab.fa-google-plus-g.fa-lg.white-text.mr-md-5.mr-3.fa-2x
          -# / Linkedin
          -# %a.li-ic
          -#   %i.fab.fa-linkedin-in.fa-lg.white-text.mr-md-5.mr-3.fa-2x
          -# / Instagram
          -# %a.ins-ic
          -#   %i.fab.fa-instagram.fa-lg.white-text.mr-md-5.mr-3.fa-2x
          / Pinterest
          -# %a.pin-ic
          -#   %i.fab.fa-pinterest.fa-lg.white-text.fa-2x
      / Grid column
    / Grid row
  / Footer Elements
  / Copyright
  .footer-copyright.text-center.py-3{ :style => "background-color: #3e8a37" }
    © 2020 Copyright:
    %a{:href => "https://mdbootstrap.com/"} MDBootstrap.com
  / Copyright
/ Footer

app/views/shared/_image_galleries.html.haml
.row
  .col-md-12.col-l2
    #mdb-lightbox-ui
    .mdb-lightbox
      - image_galleries.each do |ig|
        %figure.col-md-12
          %a{"data-size" => "1600x1067", :href => "#{ig.try(:image).url(:thumb).to_s}"}
            %img.img-fluid{:alt => "picture", :src => "#{ig.try(:image).url(:thumb).to_s}"}/

app/views/shared/_list_of_projects.html.haml
%ul.list-group
  %li.list-group-item.active{ :style => "background-color:#449c3c" } 
    %center
      LIST OF PROJECTS
- available_locations.each do |available_location|
  - if location(available_location).present?
    %li.list-group-item
      %span{ :style => "color:#6dbb65" }
        = "#{location(available_location)}"
      %ul.list-group
      - units(available_location).each do |unit|
        %li.list-group-item.d-flex.justify-content-between.align-items-center
          = link_to "Amaia #{unit.try(:type).try(:name)}  #{unit.try(:specific_location)}", unit_path(unit.id), style: "color:black"
          -# %span.badge.badge-pill{ :style => "background-color:black" } >

app/views/shared/_nav.html.haml
%nav.navbar.navbar-expand-lg.navbar-dark
  %a.navbar-brand{:href => "#"}
    = image_tag 'logo.png', width: 100
  %button.navbar-toggler{"aria-controls" => "navbarText", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarText", "data-toggle" => "collapse", :type => "button"}
    %span.navbar-toggler-icon
  #navbarText.collapse.navbar-collapse
    %ul.navbar-nav.mr-auto
      %li.nav-item{ class: "#{current_page('home')}" }
        = link_to "LIST OF PROJECTS", root_path, class: "nav-link", style: 'color:black'
      %li.nav-item{ class: "#{current_page('about_us')}" }
        = link_to "ABOUT US", about_path, class: 'nav-link', style: 'color:black'
      %li.nav-item{ class: "#{current_page('pre_selling')}" }
        = link_to "PRE SELLING", pre_selling_path, class: 'nav-link', style: 'color:black'
      %li.nav-item{ class: "#{current_page('ready_for_occupancy')}" }
        = link_to "READY FOR OCCUPANCY", ready_for_occupancy_path, class: 'nav-link', style: 'color:black'
      %li.nav-item{ class: "#{current_page('promos')}" }
        = link_to "PROMOS", promos_path, class: "nav-link", style: 'color:black'
      %li.nav-item{ class: "#{current_page('new')}" }
        = link_to "CONTACT US", new_contact_path, class: 'nav-link', style: 'color:black'
      %li.nav-item{ class: "#{current_page('index')}" }
        = link_to "SELLERS", sellers_path, class: 'nav-link', style: 'color:black'
      

app/views/shared/_unit_types.html.haml
%br/
- @unit_types.each do |unit_type|
  .container
    %h2
      = "Amaia "+ unit_type.try(:name)
    %hr
    .row.row-cols-md-3
      - unit_type.units.each do |unit|
        .col-md-4.col-lg-4.col-sm-6.col-xs-12
          .col.mb-4
            .card
              .animationLoading
                .view.overlay.image-loader
                  #image-loader
                .view-ovelay.actual-image{ style:"display:none;" }
                  %a{:href => "/unit/#{unit.try(:id)}"}
                    %img.card-img-top.unit-img{:alt => "Card image cap", :src => "#{unit.try(:image).url(:thumb).to_s}"}/
                  %a{:href => "#!"}
                    .mask.rgba-white-slight
                .card-body
                  %h4.card-title 
                    = unit.try(:branch_address)
                  .location-info-loader
                    %p.card-text
                      %span
                        #specific-location-loader
                    %hr/
                    %p.card-text
                      %span
                        #location-loader
                      %span
                        #price-range-loader
                      %span
                        #unit-sizes-loader
                  .actual-location-info
                    %p.card-text
                      %h5#unit-name-and-type
                        = link_to "Amaia #{unit.type.try(:name)} #{unit.try(:specific_location)}", unit_path(unit.try(:id)), style: 'color:gray'
                    %hr/  
                    %p.card-text
                      %span.location-txt
                        = "<b>Location: </b>".html_safe + unit.try(:city).try(:name)
                      %br/
                      %span.price-range-txt
                        = "<b>Price Range: </b>".html_safe + number_to_currency_peso(unit.try(:price_from)) + " to " + number_to_currency_peso(unit.try(:price_to))
                      %br/
                      %span.unit-sizes-txt
                        = "<b>Unit Sizes: </b>".html_safe + unit.try(:unit_size_from) + " sqm to " + unit.try(:unit_size_to) + " sqm"